export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const RESTAURANT_REGISTER_SUCCESS = "RESTAURANT_REGISTER_SUCCESS";
export const RESTAURANT_REGISTER_FAIL = "RESTAURANT_REGISTER_FAIL";
export const RESTAURANT_LOGIN_SUCCESS = "RESTAURANT_LOGIN_SUCCESS";
export const RESTAURANT_LOGIN_FAIL = "RESTAURANT_LOGIN_FAIL";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
