export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const RESTAURANT_REGISTER_SUCCESS = "RESTAURANT_REGISTER_SUCCESS";
export const RESTAURANT_REGISTER_FAIL = "RESTAURANT_REGISTER_FAIL";
export const RESTAURANT_LOGIN_SUCCESS = "RESTAURANT_LOGIN_SUCCESS";
export const RESTAURANT_LOGIN_FAIL = "RESTAURANT_LOGIN_FAIL";

export const GET_ALL_DISHES = "GET_ALL_DISHES";
export const ADD_DISH = "ADD_DISH";
export const DELETE_DISH = "DELETE_DISH";
export const GET_DISH_BY_ID = "GET_DISH_BY_ID";
export const EDIT_DISH = "EDIT_DISH";

export const GET_ALL_ORDERS_BY_REST_ID = "GET_ALL_ORDERS_BY_REST_ID";
export const VIEW_ORDER = "VIEW_ORDER";
export const UPDATE_DELIVERY_STATUS = "UPDATE_DELIVERY_STATUS";
export const GET_DISHES_OF_ORDER = "GET_DISHES_OF_ORDER";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
